### ISSUE TITLE
Safari: "Home" when wide puts the request graph below a column of widgets

### ISSUE THREAD

**Issue by skaes** [skaes/logjam_core#53]
see attached screenshot.

![screen shot 2014-11-02 at 00 07 24](https://cloud.githubusercontent.com/assets/17514/4873687/d28fa8f6-621f-11e4-9e97-9bcf9aa11b66.png)

**Comment by janwiemers** [comment]
hey @skaes works now for me, can you please double check it, if it even works on safari 7?

**Comment by skaes** [comment]
fixed.
