### ISSUE TITLE
dynamic sizing of graphs still not working correctly

### ISSUE THREAD

**Issue by skaes** [skaes/logjam_core#58]
See attached screenshot: 
![screen shot 2014-12-09 at 16 47 26](https://cloud.githubusercontent.com/assets/17514/5360218/2664a89e-7fc3-11e4-96ba-c6b64cee15f2.png)

**Comment by janwiemers** [comment]
> what happens if an exception name needs more than 50px for display?
nothing everything is fine, I just need a fixed dimension to draw the table over the full with.

> BTW, the layout of the table header got borked with the commit.
> First header cell should be left aligned, second cell right aligned.
fixed
